require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FedoraResourcesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FedoraResource. As you add validations to FedoraResource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FedoraResourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all fedora_resources as @fedora_resources" do
      fedora_resource = FedoraResource.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:fedora_resources)).to eq([fedora_resource])
    end
  end

  describe "GET #show" do
    it "assigns the requested fedora_resource as @fedora_resource" do
      fedora_resource = FedoraResource.create! valid_attributes
      get :show, params: {id: fedora_resource.to_param}, session: valid_session
      expect(assigns(:fedora_resource)).to eq(fedora_resource)
    end
  end

  describe "GET #new" do
    it "assigns a new fedora_resource as @fedora_resource" do
      get :new, params: {}, session: valid_session
      expect(assigns(:fedora_resource)).to be_a_new(FedoraResource)
    end
  end

  describe "GET #edit" do
    it "assigns the requested fedora_resource as @fedora_resource" do
      fedora_resource = FedoraResource.create! valid_attributes
      get :edit, params: {id: fedora_resource.to_param}, session: valid_session
      expect(assigns(:fedora_resource)).to eq(fedora_resource)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FedoraResource" do
        expect {
          post :create, params: {fedora_resource: valid_attributes}, session: valid_session
        }.to change(FedoraResource, :count).by(1)
      end

      it "assigns a newly created fedora_resource as @fedora_resource" do
        post :create, params: {fedora_resource: valid_attributes}, session: valid_session
        expect(assigns(:fedora_resource)).to be_a(FedoraResource)
        expect(assigns(:fedora_resource)).to be_persisted
      end

      it "redirects to the created fedora_resource" do
        post :create, params: {fedora_resource: valid_attributes}, session: valid_session
        expect(response).to redirect_to(FedoraResource.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved fedora_resource as @fedora_resource" do
        post :create, params: {fedora_resource: invalid_attributes}, session: valid_session
        expect(assigns(:fedora_resource)).to be_a_new(FedoraResource)
      end

      it "re-renders the 'new' template" do
        post :create, params: {fedora_resource: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fedora_resource" do
        fedora_resource = FedoraResource.create! valid_attributes
        put :update, params: {id: fedora_resource.to_param, fedora_resource: new_attributes}, session: valid_session
        fedora_resource.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested fedora_resource as @fedora_resource" do
        fedora_resource = FedoraResource.create! valid_attributes
        put :update, params: {id: fedora_resource.to_param, fedora_resource: valid_attributes}, session: valid_session
        expect(assigns(:fedora_resource)).to eq(fedora_resource)
      end

      it "redirects to the fedora_resource" do
        fedora_resource = FedoraResource.create! valid_attributes
        put :update, params: {id: fedora_resource.to_param, fedora_resource: valid_attributes}, session: valid_session
        expect(response).to redirect_to(fedora_resource)
      end
    end

    context "with invalid params" do
      it "assigns the fedora_resource as @fedora_resource" do
        fedora_resource = FedoraResource.create! valid_attributes
        put :update, params: {id: fedora_resource.to_param, fedora_resource: invalid_attributes}, session: valid_session
        expect(assigns(:fedora_resource)).to eq(fedora_resource)
      end

      it "re-renders the 'edit' template" do
        fedora_resource = FedoraResource.create! valid_attributes
        put :update, params: {id: fedora_resource.to_param, fedora_resource: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested fedora_resource" do
      fedora_resource = FedoraResource.create! valid_attributes
      expect {
        delete :destroy, params: {id: fedora_resource.to_param}, session: valid_session
      }.to change(FedoraResource, :count).by(-1)
    end

    it "redirects to the fedora_resources list" do
      fedora_resource = FedoraResource.create! valid_attributes
      delete :destroy, params: {id: fedora_resource.to_param}, session: valid_session
      expect(response).to redirect_to(fedora_resources_url)
    end
  end

end
